project:
  type: website
  execute-dir: project
  output-dir: _site
  render:
    - "index.qmd"
    - "tests/failure.qmd"
    # -  "!failure.qmd"

website:
  title: "svg-issue"
  navbar:
    left:
      - href: index.qmd
        text: compile-info
      - href: tests/failure.qmd
        text: failing compilation


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
  pdf: default


